### ISSUE TITLE
I believe the bootstrapping process has an error:

### ISSUE THREAD

**Issue by DominikBaer** [ibm-ecm/container-cpe#3]
java -Dfile.encoding=utf-8 -jar BootstrapConfig.jar -s FNGCDDS -x FNGCDDS -u P8Admin -p IBMFileNetP8 -e BootstrapConfigProps.jar -b 256 -c AES -k -o true

I think this is wrong it should mean:

java -Dfile.encoding=utf-8 -jar BootstrapConfig.jar -s FNGCDDS -x FNGCDDS**XA** -u P8Admin -p IBMFileNetP8 -e BootstrapConfigProps.jar -b 256 -c AES -k -o true

**Comment by wukaiying** [comment]
Thanks,we have fixed this issue.
